'use client';
import {useMemo,useState} from 'react';
import {ExternalLink,ShieldCheck,Search,CalendarDays} from 'lucide-react';
import {scholarships} from '@/lib/data';
export default function Scholarships(){
 const [q,setQ]=useState('');const [level,setLevel]=useState('All');const [region,setRegion]=useState('All');const [cat,setCat]=useState('All');
 const categories=['All',...Array.from(new Set(scholarships.map(s=>s.category)))];
 const shown=useMemo(()=>scholarships.filter(s=>(level==='All'||s.level.includes(level))&&(region==='All'||s.region.includes(region)||s.category===region)&&(cat==='All'||s.category===cat)&&(s.name+s.provider+s.summary+s.region+s.level.join(' ')).toLowerCase().includes(q.toLowerCase())),[q,level,region,cat]);
 return <><section className="page-hero rich-hero"><div className="container"><span className="eyebrow">🎓 Verified Scholarship Hub</span><h1>Find funding without the confusion.</h1><p>Explore Balochistan, Pakistan and abroad opportunities by education level. Directorate reserved-seat routes, HEC/BEEF pathways and major international scholarships are separated so students can understand what each route actually is.</p><div className="notice success"><ShieldCheck size={15}/> We do not treat AI guesses as scholarship facts. Check the official provider before submitting anything.</div></div></section>
 <section className="section"><div className="container"><div className="scholarship-tools"><div className="search-box"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search scholarship, country, provider or test…"/></div><select value={level} onChange={e=>setLevel(e.target.value)}><option>All</option><option>Intermediate</option><option>BS / Undergraduate</option><option>Masters</option><option>PhD</option></select><select value={region} onChange={e=>setRegion(e.target.value)}><option>All</option><option>Balochistan</option><option>Pakistan</option><option>China</option><option>Türkiye</option><option>Hungary</option><option>Europe</option><option>United Kingdom</option><option>United States</option><option>Worldwide</option></select><select value={cat} onChange={e=>setCat(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="scholarship-grid">{shown.map(s=><article className="card scholarship-card" key={s.id}><div className="card-top"><span className="tag">{s.category}</span><span className="verified-pill"><ShieldCheck size={12}/> Verified {s.verified}</span></div><h3>{s.name}</h3><p><strong>{s.provider}</strong> · {s.region}</p><p>{s.summary}</p><div className="meta">{s.level.map(x=><span key={x}>{x}</span>)}</div><div className="mini-block"><strong>Current status</strong><p>{s.status}</p></div><div className="mini-block"><strong>Eligibility</strong><ul>{s.eligibility.slice(0,4).map(x=><li key={x}>{x}</li>)}</ul></div><div className="mini-block"><strong>Funding / support</strong><ul>{s.funding.slice(0,3).map(x=><li key={x}>{x}</li>)}</ul></div>{s.deadline&&<div className="deadline"><CalendarDays size={14}/>{s.deadline}</div>}<div className="card-actions"><a className="btn btn-secondary" href={s.source} target="_blank" rel="noreferrer">Official source <ExternalLink size={13}/></a><a className="btn btn-primary" href={s.apply} target="_blank" rel="noreferrer">Apply / portal <ExternalLink size={13}/></a></div></article>)}</div>{!shown.length&&<div className="empty-state"><h3>No matching scholarships</h3><p>Try a broader search or select “All”. If an opportunity is not in TaleemAI's verified dataset, we won't invent one.</p></div>}</div></section></>;
}
