import Link from 'next/link';
import {ArrowRight, Bot, GraduationCap, MapPin, Search, ShieldCheck, Sparkles} from 'lucide-react';
import {scholarships,careers,skills} from '@/lib/data';
import {ScholarshipCard} from '@/components/ScholarshipCard';
export default function Home(){return <>
<section className="hero"><div className="container hero-grid"><div><span className="eyebrow"><Sparkles size={14}/> Balochistan-first · Pakistan-ready</span><h1>Your future.<br/><em>Your opportunities.</em><br/>One guide.</h1><p>Find scholarships, careers, universities, skills and study-abroad pathways — explained simply in English and Urdu.</p><div className="hero-actions"><Link className="btn btn-primary" href="/mentor"><Bot size={17}/> Ask TaleemAI</Link><Link className="btn btn-secondary" href="/scholarships"><GraduationCap size={17}/> Find scholarships</Link></div><div className="hero-note">Free for students · No signup required · Verified sources shown on opportunity pages</div></div><div className="hero-card"><span className="eyebrow">🤖 Student example</span><h3>“Mere paas fees ke paise nahi hain.”</h3><p>TaleemAI turns a vague problem into a practical roadmap.</p><div className="profile-row"><span className="chip">Balochistan</span><span className="chip">FSC 78%</span><span className="chip">Low budget</span></div><div className="match"><strong>1 · Check BEEF</strong><small>Current scheme + education level determine eligibility.</small></div><div className="match"><strong>2 · Check HEC funding</strong><small>Need-based and Balochistan-specific pathways.</small></div><div className="match"><strong>3 · Build a backup plan</strong><small>Free skills + university financial aid.</small></div></div></div></section>
<section className="section"><div className="container"><div className="section-head"><div><h2>What do you need today?</h2><p>You don't need to know the scholarship name or career name. Tell TaleemAI your situation.</p></div></div><div className="grid-4">{[['🎓','I need a scholarship','/scholarships'],['🧭','I don’t know what to study','/careers'],['🏫','I need a university','/universities'],['🌍','I want to study abroad','/abroad'],['💻','I want a free skill','/skills'],['📝','I need BBISE help','/bbise'],['📍','I’m from Balochistan','/balochistan'],['🤖','Talk to the AI Mentor','/mentor']].map(([i,t,h])=><Link href={h} className="card feature-card" key={h}><div className="icon-box">{i}</div><h3>{t}</h3><p>Simple guidance, next steps and official resources.</p><span>Explore <ArrowRight size={14}/></span></Link>)}</div></div></section>
<section className="section alt"><div className="container"><div className="section-head"><div><h2>Scholarships worth knowing</h2><p>We separate Balochistan, Pakistan and international routes — and show when a program is for your stage.</p></div><Link className="btn btn-secondary" href="/scholarships">View all</Link></div><div className="grid-3">{scholarships.slice(0,3).map(s=><ScholarshipCard key={s.id} s={s}/>)}</div></div></section>
<section className="section"><div className="container"><div className="banner"><div><span className="eyebrow">🇵🇰 Balochistan first</span><h2>From Pishin to Gwadar, your district matters.</h2><p>Scholarship eligibility can depend on domicile, where you studied, your marks and your district. TaleemAI puts those details first.</p></div><Link className="btn btn-primary" href="/balochistan">Open Balochistan guide <ArrowRight size={15}/></Link></div></div></section>
<section className="section"><div className="container"><div className="section-head"><div><h2>Learn skills without waiting for a job</h2><p>Start building evidence of skill: projects, portfolio, communication and practical work.</p></div><Link className="btn btn-secondary" href="/skills">Explore skills</Link></div><div className="grid-3">{skills.slice(0,3).map(x=><div className="card" key={x.name}><div className="icon-box">💡</div><h3>{x.name}</h3><p>{x.level}</p><p style={{marginTop:8}}>{x.outcome}</p></div>)}</div></div></section>
<section className="section alt"><div className="container"><div className="two-col"><div><span className="eyebrow"><ShieldCheck size={14}/> Trust layer</span><h2>Official source, simple explanation.</h2><p className="muted">TaleemAI should never invent a scholarship, deadline or eligibility rule. Each opportunity shows its official source and last verification date.</p></div><div className="card"><h3>Reality check</h3><ul className="checklist"><li>A scholarship does not guarantee admission.</li><li>A degree does not guarantee a job.</li><li>“Fully funded” can mean different things; check the official terms.</li><li>Deadlines change. Always verify before submitting.</li></ul></div></div></div></section>
</>}
