'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
export function Footer(){
  const pathname=usePathname();
  const urdu=pathname==='/ur'||pathname.startsWith('/ur/');
  const p=(x:string)=>urdu?(x==='/'?'/ur':`/ur${x}`):x;
  return <footer className="footer"><div className="container footer-grid"><div><div className="footer-logo"><img src="/icon.svg" alt="TaleemAI"/><span>Taleem<span>AI</span></span></div><p>{urdu?'بلوچستان سے پاکستان اور دنیا تک — طلبہ کے لیے آسان، bilingual education guidance۔':'From Balochistan to Pakistan to the world — simple, bilingual education guidance for students.'}</p><p className="muted">{urdu?'یہ معلومات educational guidance ہیں؛ admission یا scholarship selection کی guarantee نہیں۔':'Information is educational guidance, not a guarantee of admission or scholarship selection.'}</p></div><div><h4>{urdu?'Explore':'Explore'}</h4><Link href={p('/scholarships')}>{urdu?'اسکالرشپس':'Scholarships'}</Link><Link href={p('/tests')}>{urdu?'Entrance Tests اور Results':'Entrance Tests & Results'}</Link><Link href={p('/careers')}>{urdu?'کیریئر راستے':'Career Paths'}</Link><Link href={p('/universities')}>{urdu?'یونیورسٹیز':'Universities'}</Link><Link href={p('/abroad')}>{urdu?'بیرونِ ملک تعلیم':'Study Abroad'}</Link><Link href={p('/skills')}>{urdu?'فری اسکلز':'Free Skills'}</Link></div><div><h4>{urdu?'طلبہ اور اداروں کے لیے':'For students & institutions'}</h4><Link href={p('/study-after-matric')}>{urdu?'میٹرک کے بعد':'After Matric'}</Link><Link href={p('/colleges')}>{urdu?'کالج ایکسپلورر':'College Explorer'}</Link><Link href={p('/bbise')}>{urdu?'BBISE Results & Services':'BBISE Results & Services'}</Link><Link href={p('/get-online')}>{urdu?'اپنا ادارہ آن لائن لائیں':'Get Your Institution Online'}</Link><a href="https://beef.org.pk/" target="_blank" rel="noreferrer">BEEF official</a><a href="https://www.hec.gov.pk/" target="_blank" rel="noreferrer">HEC official</a></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} TaleemAI</span><span>{urdu?'Source review: 1 Oct 2026':'Source review: 1 Oct 2026'}</span></div></footer>
}
