export type Scholarship={
  id:string; name:string; provider:string; level:string[]; region:string; category:string; status:string; deadline?:string;
  summary:string; eligibility:string[]; funding:string[]; source:string; apply:string; verified:string; urdu:string;
};

export const verifiedDate='29 September 2026';

export const scholarships:Scholarship[]=[
 {id:'hec-bf3',name:'HEC Balochistan & Erstwhile FATA Undergraduate Scholarship — Phase III',provider:'Higher Education Commission (HEC)',level:['BS / Undergraduate'],region:'Balochistan',category:'Balochistan',status:'Check next/current call',deadline:'Previous batch deadline: 23 Oct 2025',summary:'A major undergraduate pathway for eligible students with Balochistan or erstwhile FATA domicile/local certificate.',eligibility:['Balochistan or erstwhile FATA domicile/local certificate as specified by HEC','12 years of education with at least 60% under the published Phase-III criteria','Age limit and other conditions apply on the advertised closing date','Cannot normally hold another HEC/Government scholarship at the same time','Admission must meet the published HEC institution requirements'],funding:['Tuition and other charges within the published limits','Living allowance and other allowances under the scheme','Exact support must be checked in the current call'],source:'https://www.hec.gov.pk/english/scholarshipsgrants/BF-III/Pages/FAQs.aspx',apply:'https://scholarship.hec.gov.pk/',verified:verifiedDate,urdu:'بلوچستان کے طلبہ کے لیے اہم undergraduate راستہ ہے۔ اگلا call آنے پر HEC کی official eligibility اور deadline ضرور دیکھیں۔'},
 {id:'beef',name:'BEEF Annual Scholarship Programs',provider:'Balochistan Education Endowment Fund (BEEF)',level:['Matric','Intermediate','DAE','BS','Professional','Masters','MS/MPhil','PhD'],region:'Balochistan',category:'Balochistan',status:'Scheme / annual policy',summary:'BEEF supports multiple education levels through different regular, partially funded and fully funded schemes.',eligibility:['Balochistan local/domicile requirement depends on the scheme','Academic and institutional rules vary by level','Some scholarships use board or institution merit information','Always read the current BEEF policy and notice'],funding:['Partially funded annual schemes exist','Fully funded schemes exist','Amount and coverage depend on the specific scheme and year'],source:'https://beef.org.pk/policyguideline/',apply:'https://beef.org.pk/',verified:verifiedDate,urdu:'BEEF صرف university کے لیے نہیں۔ اس کی مختلف schemes Matric سے higher studies تک جا سکتی ہیں۔ ہر scheme کی شرط الگ ہو سکتی ہے۔'},
 {id:'coastal',name:'Coastal Region Higher Education Scholarship for Balochistan',provider:'HEC',level:['BS / Undergraduate'],region:'Gwadar, Lasbela/Hub, Kech (Turbat), Awaran',category:'Coastal Balochistan',status:'Check current batch',summary:'HEC support for eligible students from the specified coastal/southern districts of Balochistan.',eligibility:['Domicile/local certificate from Gwadar, Lasbela/Hub, Kech (Turbat) or Awaran','Published batch requirements include SSC and HSSC academic conditions','District and study-location conditions apply','Age and other conditions apply on the closing date'],funding:['Tuition and other charges within published limits','Living allowance','Books/travel support within published limits','Hostel-related support subject to the scheme'],source:'https://www.hec.gov.pk/english/scholarshipsgrants/CRHES/Pages/Eligibility-Criteria.aspx',apply:'https://scholarship.hec.gov.pk/',verified:verifiedDate,urdu:'گوادر، لسبیلہ/حب، کیچ اور آواران کے eligible طلبہ کے لیے HEC کا الگ undergraduate راستہ ہے۔'},
 {id:'hec-need',name:'HEC Need-Based Scholarship',provider:'HEC + participating universities',level:['BS / Undergraduate'],region:'Pakistan',category:'Pakistan',status:'Institution-based',summary:'Financial assistance for financially needy undergraduate students at participating public-sector institutions.',eligibility:['Financial need is assessed by the participating university','You need admission/enrolment at an eligible institution','Program and institution rules apply','Apply through the university Financial Aid Office where instructed'],funding:['Tuition support according to allocation and university rules','Published HEC information includes a monthly stipend for grantees'],source:'https://www.hec.gov.pk/english/scholarshipsgrants/NBS/Pages/Eligibility-Criteria.aspx',apply:'https://www.hec.gov.pk/english/scholarshipsgrants/NBS/Pages/How-To-Apply.aspx',verified:verifiedDate,urdu:'اگر university کی fee مشکل ہے تو admission کے بعد Financial Aid Office سے HEC Need-Based کے بارے میں ضرور پوچھیں۔'},
 {id:'csc',name:'Chinese Government Scholarship (CSC) — HEC Type-A',provider:'Government of China / China Scholarship Council + HEC',level:['BS / Undergraduate','Masters','PhD'],region:'China',category:'BS Abroad',status:'2026–27 cycle closed; prepare for next call',deadline:'HEC deadline for 2026–27: 5 Jan 2026',summary:'HEC-nominated Chinese Government Scholarship route. The 2026–27 HEC listing included 35 Bachelor, 25 Master and 15 PhD seats.',eligibility:['Pakistani applicants meeting the published HEC and CSC criteria','Level-specific age, academic and document rules apply','CSCA is mandatory for undergraduate applicants seeking admission in China','Type-A HEC nomination is different from direct Type-B applications'],funding:['Funding depends on the published CSC award terms','University tuition and other support are subject to the scholarship terms'],source:'https://www.hec.gov.pk/english/scholarshipsgrants/lao/CGSP/Pages/default.aspx',apply:'https://scholarship.hec.gov.pk/',verified:verifiedDate,urdu:'China کی CSC scholarship میں BS، Masters اور PhD کے راستے ہو سکتے ہیں۔ BS applicants کے لیے CSCA requirement خاص طور پر اہم ہے۔'},
 {id:'turkiye',name:'Türkiye Scholarships',provider:'Government of Türkiye / YTB',level:['Associate','BS / Undergraduate','Masters','PhD'],region:'Türkiye',category:'BS Abroad',status:'Annual — check current call',summary:'Government-funded scholarship route for international students across multiple degree levels.',eligibility:['International students including Pakistanis can apply subject to the call','Academic and age requirements vary by level','Program-specific requirements must be checked on the official portal'],funding:['University/department placement where applicable','Tuition fee','Monthly stipend','Accommodation','Health insurance','Flight support and language preparation according to official terms'],source:'https://www.turkiyeburslari.gov.tr/scholarshipsprograms',apply:'https://www.turkiyeburslari.gov.tr/',verified:verifiedDate,urdu:'Türkiye کی سرکاری scholarship مختلف levels کے لیے ہے۔ ہر level کی age اور academic requirements الگ ہو سکتی ہیں۔'},
 {id:'erasmus',name:'Erasmus Mundus Joint Masters',provider:'European Union / Erasmus+',level:['Masters'],region:'Europe',category:'Masters Abroad',status:'Usually applications run Oct–Jan',summary:'Joint Master’s programs delivered by international university consortia. Selected programs offer full scholarships.',eligibility:['Bachelor’s degree or program-specific equivalent','Each joint master has its own requirements','Students apply to the specific program/consortium','Deadlines are set by individual programs'],funding:['Selected programs offer full scholarships','Participation costs and contributions toward travel, visa and living are covered according to the award'],source:'https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters',apply:'https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters',verified:verifiedDate,urdu:'Bachelor کے بعد Europe کے joint Master programs میں scholarship کے مواقع ہوتے ہیں۔ ہر program کی اپنی eligibility اور deadline ہوتی ہے۔'},
 {id:'commonwealth',name:'Commonwealth Scholarships — Pakistan',provider:'Commonwealth Scholarship Commission / HEC',level:['Masters','PhD'],region:'United Kingdom',category:'Masters Abroad',status:'Cycle-based — check HEC + Commonwealth',summary:'UK postgraduate scholarship route for eligible Pakistani applicants. Some awards are applied for through both the Commonwealth and HEC processes.',eligibility:['Level-specific academic and citizenship requirements','HEC nomination requirements apply for HEC-nominated awards','Application steps and deadlines vary by cycle'],funding:['Award coverage depends on the specific Commonwealth scheme','Check the official award terms for tuition, living, travel and other support'],source:'https://www.hec.gov.pk/english/HECAnnouncements/Pages/CW-Scholarship.aspx',apply:'https://www.hec.gov.pk/english/HECAnnouncements/Pages/CW-Scholarship.aspx',verified:verifiedDate,urdu:'Commonwealth کے مختلف postgraduate routes ہیں۔ پاکستان سے HEC nomination اور official Commonwealth instructions دونوں دیکھنا ضروری ہے۔'},
 {id:'fulbright',name:'Fulbright Degree Program — Pakistan',provider:'USEFP',level:['Masters','PhD'],region:'United States',category:'Masters Abroad',status:'Annual — next cycle check official page',summary:'U.S. graduate study scholarship administered in Pakistan by USEFP.',eligibility:['Pakistani citizen residing in Pakistan','Masters requires 16 years of formal education','PhD requires 18 years of formal education','GRE General is required under the published program rules','Clinical medicine is excluded','English proficiency and program-specific requirements apply'],funding:['Tuition','Required textbooks','Airfare','Living stipend','Health insurance under program terms'],source:'https://www.usefp.org/scholarships/fulbright-degree.cfm',apply:'https://www.usefp.org/scholarships/fulbright-degree.cfm',verified:verifiedDate,urdu:'Fulbright پاکستان سے US میں Master یا PhD کے لیے ہے۔ یہ FSC کے بعد direct undergraduate scholarship نہیں ہے۔'},
 {id:'chevening',name:'Chevening Scholarship — Pakistan',provider:'UK Government / Chevening',level:['Masters'],region:'United Kingdom',category:'Masters Abroad',status:'2027–28 cycle open at verification',deadline:'6 Oct 2026, 11:00 UTC',summary:'UK government scholarship for eligible applicants pursuing a one-year master’s degree.',eligibility:['Eligible-country citizenship requirement','Undergraduate degree suitable for a UK master’s','At least 2,800 hours of work experience under current eligibility guidance','Apply to three eligible UK courses','Return-home commitment under the scholarship rules'],funding:['Scholarship support according to the official Chevening award terms'],source:'https://www.chevening.org/resource-hub/guidance/eligibility/',apply:'https://www.chevening.org/scholarships/application-timeline/',verified:verifiedDate,urdu:'Chevening undergraduate beginners کے لیے نہیں۔ Bachelor کے بعد work experience اور دوسری eligibility requirements ضروری ہیں۔'}
];

export const studyAfterMatric=[
 {id:'fsc',name:'F.Sc.',short:'Science route',icon:'🔬',best:'Medicine, engineering, natural sciences and many science degrees.',what:'Pre-Medical and Pre-Engineering are common pathways; exact subject combinations depend on the board/college.',next:'Check the colleges available in your district and the subjects they actually offer.',source:'https://bbiseqta.edu.pk/'},
 {id:'ics',name:'I.C.S.',short:'Computer route',icon:'💻',best:'Computer Science, IT, software and other computing-related degrees.',what:'Combines computer studies with mathematics/science subjects depending on the offered group.',next:'Check university admission rules too, because degree eligibility can differ.',source:'https://bbiseqta.edu.pk/'},
 {id:'fa',name:'F.A.',short:'Humanities route',icon:'📚',best:'Humanities, social sciences, education, languages and related fields.',what:'Subject combinations vary by college and board.',next:'Choose subjects that match the degree or career you may want later.',source:'https://bbiseqta.edu.pk/'},
 {id:'icom',name:'I.Com',short:'Commerce route',icon:'📊',best:'Accounting, finance, commerce, business and related degrees.',what:'A commerce-focused intermediate pathway.',next:'Compare it with FA/FSc/ICS based on your intended degree.',source:'https://bbiseqta.edu.pk/'},
 {id:'dae',name:'DAE',short:'Technical diploma',icon:'🔧',best:'Practical technical and engineering-related education.',what:'NAVTTC lists DAE/conventional qualifications and technical curricula; local admission rules vary.',next:'Check the specific technology, institute and board rules before enrolling.',source:'https://navttc.gov.pk/track/conventional/'},
 {id:'tvet',name:'TVET / Skills',short:'Practical skills',icon:'🛠️',best:'Students who want practical training, certification and job-oriented skills.',what:'NAVTTC offers and catalogs vocational qualifications and short courses across many sectors.',next:'Search the official NAVTTC student and institute portals for current openings.',source:'https://navttc.gov.pk/student/'}
];

export const colleges=[
 {id:'fgdc-quetta',name:'FG Degree College Quetta Cantt (Boys)',district:'Quetta',type:'Government-supervised college',programs:['F.Sc. Pre-Engineering','F.Sc. Pre-Medical','I.C.S.','F.A.','BS English'],image:'https://fgbdcqta.edu.pk/wp-content/uploads/2025/05/main-gate_11zon-scaled.jpg',source:'https://fgbdcqta.edu.pk/',note:'The college website currently lists intermediate and BS offerings and provides admission/fee links. Verify the current admission notice before applying.'},
 {id:'fg-girls-quetta',name:'FG Girls Degree College Quetta Cantt',district:'Quetta',type:'Government college',programs:['F.Sc. Pre-Engineering','F.Sc. Pre-Medical','I.C.S.','F.A.','BS English'],image:'https://fggdcqta.edu.pk/wp-content/uploads/2025/07/Principal-Pics.jpeg',source:'https://fggdcqta.edu.pk/',note:'The official site lists intermediate and BS programs and current admission notices. The displayed image is from the college website.'},
 {id:'cadet-pishin',name:'Cadet College Pishin',district:'Pishin',type:'Balochistan government cadet college',programs:['SSC','HSSC'],image:'https://www.ccpn.edu.pk/wp-content/uploads/2024/08/slider1.jpg',source:'https://www.ccpn.edu.pk/',note:'The official site describes SSC/HSSC education, residential facilities and the college’s governance under Balochistan. Verify admissions from the current prospectus.'},
 {id:'govt-degree-pishin',name:'Government Degree College Pishin',district:'Pishin',type:'Government degree college',programs:['Intermediate / degree programs vary by current notice'],image:'',source:'https://www.uob.edu.pk/AffilatedColleges.php',note:'The University of Balochistan lists Government Degree College Pishin among affiliated colleges. Current programs and admissions should be checked with the college.'}
];

export const governmentResources=[
 {name:'Balochistan Education Endowment Fund (BEEF)',type:'Scholarships / financial support',desc:'Provincial scholarship schemes across multiple education levels.',url:'https://beef.org.pk/policyguideline/'},
 {name:'Higher Education Commission (HEC)',type:'University scholarships / study abroad',desc:'National scholarships, foreign-funded opportunities and higher-education information.',url:'https://www.hec.gov.pk/english/scholarshipsgrants/Pages/default.aspx'},
 {name:'NAVTTC',type:'Technical & vocational training',desc:'Government skills, qualifications, courses, institute discovery and certification information.',url:'https://navttc.gov.pk/'},
 {name:'BBISE Quetta',type:'Board services',desc:'Balochistan board information, forms and student services.',url:'https://bbiseqta.edu.pk/'},
 {name:'Colleges, Higher & Technical Education Balochistan',type:'Provincial education',desc:'Official provincial gateway for colleges, higher and technical education.',url:'https://chte.balochistan.gov.pk/'},
 {name:'Pakistan Bait-ul-Mal',type:'Education assistance',desc:'Public assistance programs including education support subject to eligibility and current rules.',url:'https://www.pbm.gov.pk/Project-IFA.html'}
];

export const districts=['Quetta','Pishin','Chaman','Killa Abdullah','Killa Saifullah','Zhob','Loralai','Ziarat','Sibi','Dera Bugti','Kohlu','Barkhan','Musakhel','Nasirabad','Jaffarabad','Khuzdar','Kalat','Mastung','Chagai','Nushki','Washuk','Kharan','Panjgur','Kech (Turbat)','Gwadar','Awaran','Lasbela / Hub'];

export const careers=[
 {name:'Computer Science',icon:'💻',fit:'For students who enjoy computers, logic and building things.',paths:'Software • AI • Data • Cybersecurity • Web',next:'Start with programming, problem solving and English.'},
 {name:'Medicine & Health',icon:'🩺',fit:'For students motivated by biology, healthcare and service.',paths:'Medicine • Pharmacy • Public Health • Allied Health',next:'Check professional council and university admission rules.'},
 {name:'Business & Finance',icon:'📊',fit:'For students interested in organizations, money and entrepreneurship.',paths:'Finance • Accounting • Marketing • Entrepreneurship',next:'Build communication, Excel and business fundamentals.'},
 {name:'Engineering',icon:'⚙️',fit:'For students who enjoy maths, physics and designing systems.',paths:'Civil • Electrical • Mechanical • Computer • Energy',next:'Check the exact university and professional accreditation rules.'},
 {name:'Education',icon:'📖',fit:'For students who enjoy teaching, communication and helping others learn.',paths:'Teaching • Education • Curriculum • Training',next:'Compare education degrees and teacher-qualification requirements.'},
 {name:'Agriculture',icon:'🌱',fit:'For students interested in food, land, water and natural resources.',paths:'Agriculture • Agribusiness • Soil • Livestock • Research',next:'Explore agriculture programs and practical field skills.'}
];

export const skills=[
 {name:'Web Development',level:'Beginner → intermediate',outcome:'Build websites and a portfolio using HTML, CSS, JavaScript and modern tools.'},
 {name:'AI & Python',level:'Beginner → intermediate',outcome:'Learn Python, AI concepts and practical automation.'},
 {name:'Digital Marketing',level:'Beginner → intermediate',outcome:'Learn SEO, content, social media and analytics.'},
 {name:'UI/UX Design',level:'Beginner → intermediate',outcome:'Learn user research, wireframes and interface design.'},
 {name:'Cybersecurity',level:'Beginner → intermediate',outcome:'Build foundations in networking, Linux and security.'},
 {name:'Freelancing',level:'Beginner',outcome:'Learn how to build a portfolio, communicate with clients and apply safely.'}
];

export const universities=[
 {name:'BUITEMS',city:'Quetta',type:'Public',focus:'Technology, engineering, management and sciences',source:'https://www.buitems.edu.pk/'},
 {name:'University of Balochistan',city:'Quetta',type:'Public',focus:'Broad range of undergraduate and postgraduate programs',source:'https://www.uob.edu.pk/'},
 {name:'Balochistan University of Engineering & Technology',city:'Khuzdar',type:'Public',focus:'Engineering and technology',source:'https://www.buetk.edu.pk/'},
 {name:'University of Turbat',city:'Turbat',type:'Public',focus:'Programs serving southern Balochistan',source:'https://uot.edu.pk/'},
 {name:'Lasbela University of Agriculture, Water & Marine Sciences',city:'Uthal',type:'Public',focus:'Agriculture, water, marine and related disciplines',source:'https://www.luawms.edu.pk/'},
 {name:'Balochistan University of Information Technology, Engineering and Management Sciences',city:'Quetta',type:'Public',focus:'Computing, engineering and management',source:'https://www.buitems.edu.pk/'}
];
