export type Scholarship={id:string;name:string;provider:string;level:string[];region:string;tag:string;status:string;deadline?:string;summary:string;eligibility:string[];funding:string[];source:string;apply:string;verified:string;urdu:string;}
export const scholarships:Scholarship[]=[
{id:'hec-bf3',name:'HEC Balochistan & Erstwhile FATA Undergraduate Scholarship — Phase III',provider:'Higher Education Commission (HEC)',level:['Undergraduate'],region:'Balochistan',tag:'Balochistan',status:'Cycle reference',deadline:'Previous Batch closed 23 Oct 2025',summary:'A major undergraduate pathway for students with Balochistan or erstwhile FATA domicile/local certificate.',eligibility:['Age ≤22 on the advertised closing date','12 years education with at least 60% in FA/FSc/I.Com/ICS/DAE or equivalent','Valid applicant and father domicile/local certificate','No other HEC/Government scholarship at the same time','Admission must be in an HEC-recognized university/institute'],funding:['Tuition and other charges including hostel up to Rs.200,000/year','Rs.12,000/month living allowance','Rs.10,000/year books','Rs.10,000/year travel','Rs.20,000 one-time settlement allowance'],source:'https://www.hec.gov.pk/english/scholarshipsgrants/BF-III/Pages/FAQs.aspx',apply:'https://scholarship.hec.gov.pk/',verified:'29 Sep 2026',urdu:'بلوچستان کے طلبہ کے لیے اہم انڈرگریجویٹ اسکالرشپ؛ اگلا call آنے پر official HEC page ضرور چیک کریں۔'},
{id:'beef',name:'BEEF Annual Scholarship Programs',provider:'Balochistan Education Endowment Fund (BEEF)',level:['School','Intermediate','DAE','BS','Professional','Masters','MS/MPhil','PhD'],region:'Balochistan',tag:'Balochistan',status:'Annual / scheme-based',summary:'BEEF supports students across multiple education levels through regular/partially funded and fully funded schemes.',eligibility:['Balochistan domicile/local eligibility depends on the specific scheme','Academic and institutional requirements vary by level','Some schemes are proactive through board/institution data','Always check the current annual policy and notice'],funding:['Regular/partially funded schemes','Fully funded schemes','Coverage varies by program and year'],source:'https://beef.org.pk/policyguideline/',apply:'https://beef.org.pk/',verified:'29 Sep 2026',urdu:'BEEF بلوچستان کے مختلف levels کے طلبہ کے لیے کئی scholarship schemes چلاتا ہے۔ ہر scheme کی eligibility الگ ہو سکتی ہے۔'},
{id:'coastal',name:'Coastal Region Higher Education Scholarship for Balochistan',provider:'HEC',level:['Undergraduate'],region:'Gwadar, Lasbela/Hub, Kech (Turbat), Awaran',tag:'Coastal Balochistan',status:'Batch IV merit process referenced',summary:'A fully funded-style undergraduate support pathway for eligible students from four coastal/southern districts.',eligibility:['Domicile/local certificate of Gwadar, Lasbela/Hub, Kech (Turbat) or Awaran','At least 50% in SSC and 50% in HSSC/equivalent','Both SSC and HSSC must be from the defined districts','Age ≤22 on closing date','Not already receiving another HEC/Government scholarship'],funding:['Tuition and other charges including hostel up to Rs.240,000/year or actual, whichever is less','Rs.15,000/month living allowance','Rs.30,000/year books and travel','Hostel-related support subject to published limits'],source:'https://www.hec.gov.pk/english/scholarshipsgrants/CRHES/Pages/default.aspx',apply:'https://scholarship.hec.gov.pk/',verified:'29 Sep 2026',urdu:'گوادر، لسبیلہ/حب، کیچ اور آواران کے اہل طلبہ کے لیے HEC کا اہم undergraduate program۔'},
{id:'need-based',name:'HEC Need-Based Scholarship',provider:'HEC + participating universities',level:['Undergraduate'],region:'Pakistan',tag:'Need-based',status:'Ongoing institutional program',summary:'Financial assistance for undergraduate students at HEC-selected public-sector universities and degree-awarding institutions.',eligibility:['Financial need assessed by the university scholarship committee','Must secure admission at a participating institution','Undergraduate 4–5 year programs','Already enrolled financially needy students may also apply','Self-finance admission is not eligible'],funding:['Tuition support according to university allocation','Rs.6,000/month stipend for grantees'],source:'https://www.hec.gov.pk/english/scholarshipsgrants/NBS/Pages/Eligibility-Criteria.aspx',apply:'https://www.hec.gov.pk/english/scholarshipsgrants/NBS/Pages/How-To-Apply.aspx',verified:'29 Sep 2026',urdu:'اگر fees کا مسئلہ ہے تو اپنی university کے Financial Aid Office سے HEC Need-Based Scholarship ضرور پوچھیں۔'},
{id:'erasmus',name:'Erasmus Mundus Joint Masters',provider:'European Union / Erasmus+',level:['Masters'],region:'Europe',tag:'Fully funded options',status:'Usually Oct–Jan',summary:'Joint master’s programs delivered by international university consortia; many programs offer full scholarships.',eligibility:['Bachelor’s degree or program-specific equivalent','Requirements differ by master’s program','Students apply directly to the consortium/program','Check each program’s own deadline'],funding:['Full scholarships are available in selected programs','Participation costs','Contribution toward travel, visa and living allowance'],source:'https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters',apply:'https://erasmus-plus.ec.europa.eu/opportunities/individuals/students/erasmus-mundus-joint-masters',verified:'29 Sep 2026',urdu:'Bachelor مکمل کرنے کے بعد مختلف European universities کے مشترکہ Master programs میں fully funded scholarship کے مواقع۔'},
{id:'turkiye',name:'Türkiye Scholarships',provider:'Government of Türkiye / YTB',level:['Associate','Bachelor','Masters','PhD'],region:'Türkiye',tag:'Fully funded',status:'Annual — commonly Jan–Feb',summary:'Government scholarship with university placement and support across undergraduate and postgraduate levels.',eligibility:['International students including Pakistanis','Academic and age criteria vary by level','Bachelor/associate minimum academic achievement currently listed at 70%','Health sciences currently listed at 90%','Undergraduate age criterion currently under 21'],funding:['University and department placement','Tuition fee','Monthly stipend','Accommodation','Health insurance','One-off flight ticket','1-year Turkish language course'],source:'https://www.turkiyeburslari.gov.tr/scholarshipsprograms',apply:'https://www.turkiyeburslari.gov.tr/',verified:'29 Sep 2026',urdu:'ترکی کی سرکاری scholarship؛ undergraduate سے PhD تک مختلف levels پر tuition، accommodation، stipend اور دیگر support دیتی ہے۔'},
{id:'fulbright',name:'Fulbright Degree Program — Pakistan',provider:'USEFP',level:['Masters','PhD'],region:'United States',tag:'Fully funded',status:'Annual — 2027 cycle closed Apr 1 2026',summary:'U.S. graduate study scholarship administered in Pakistan by USEFP.',eligibility:['Pakistani citizen residing in Pakistan','Masters: 16 years formal education','PhD: 18 years formal education','GRE General required','Clinical medicine excluded','English proficiency required'],funding:['Tuition','Required textbooks','Airfare','Living stipend','Health insurance'],source:'https://www.usefp.org/scholarships/fulbright-degree.cfm',apply:'https://www.usefp.org/scholarships/fulbright-degree.cfm',verified:'29 Sep 2026',urdu:'پاکستانی طلبہ کے لیے US میں Master/PhD کی fully funded graduate scholarship؛ اگلے cycle کی official date دیکھیں۔'},
{id:'chevening',name:'Chevening Scholarship — Pakistan',provider:'UK Government / Chevening',level:['Masters'],region:'United Kingdom',tag:'Fully funded',status:'Open — 2027–28 cycle',deadline:'6 Oct 2026, 11:00 UTC',summary:'UK government scholarship for eligible Pakistani applicants pursuing a one-year master’s degree.',eligibility:['Pakistani citizen / eligible country requirement','Undergraduate degree qualifying for a UK master’s','At least 2,800 hours of work experience after undergraduate degree','Apply to three eligible UK courses','Commit to returning to home country for at least two years'],funding:['UK master’s study support under the Chevening award terms','Travel and living support according to official award terms'],source:'https://www.chevening.org/scholarship/pakistan/',apply:'https://www.chevening.org/scholarship/pakistan/',verified:'29 Sep 2026',urdu:'یہ FSC/BS beginners کے لیے نہیں؛ Bachelor کے بعد required work experience کے ساتھ UK Master کے لیے ہے۔'}
];

export const districts=['Quetta','Pishin','Chaman','Killa Abdullah','Killa Saifullah','Zhob','Loralai','Ziarat','Sibi','Dera Bugti','Kohlu','Barkhan','Musakhel','Nasirabad','Jaffarabad','Khuzdar','Kalat','Mastung','Chagai','Nushki','Washuk','Kharan','Panjgur','Kech (Turbat)','Gwadar','Awaran','Lasbela / Hub'];
export const careers=[
{name:'Computer Science',icon:'💻',fit:'For students who enjoy computers, logic and building things.',paths:'Software • AI • Data • Cybersecurity • Web',next:'Start with programming, problem solving and English.'},
{name:'Software Engineering',icon:'🧩',fit:'For students who want to design and build reliable software.',paths:'Web • Mobile • Cloud • QA • Product',next:'Learn programming + Git + projects.'},
{name:'AI & Data Science',icon:'🤖',fit:'For students interested in maths, data and intelligent systems.',paths:'AI • ML • Data • Research',next:'Strengthen maths, Python and statistics.'},
{name:'Cybersecurity',icon:'🔐',fit:'For students curious about systems, networks and security.',paths:'SOC • Security • Networks • Risk',next:'Learn networking, Linux and security fundamentals.'},
{name:'Medicine & Health',icon:'🩺',fit:'For students motivated by biology, healthcare and service.',paths:'Medicine • Pharmacy • Public Health • Allied Health',next:'Check professional council and university admission rules.'},
{name:'Business & Finance',icon:'📊',fit:'For students interested in markets, organizations and entrepreneurship.',paths:'Finance • Accounting • Marketing • Entrepreneurship',next:'Build communication, Excel and business fundamentals.'},
{name:'Engineering',icon:'⚙️',fit:'For students who enjoy maths, physics and solving practical problems.',paths:'Civil • Electrical • Mechanical • Computer',next:'Compare accreditation and university program requirements.'},
{name:'Education',icon:'📚',fit:'For students interested in teaching, learning and community impact.',paths:'Teaching • Curriculum • Education leadership',next:'Explore subject specialization and teacher-education routes.'}
];

export const universities=[
{name:'BUITEMS',city:'Quetta',type:'Public',focus:'Technology, engineering, management and sciences',source:'https://www.buitems.edu.pk/'},
{name:'University of Balochistan',city:'Quetta',type:'Public',focus:'Broad range of undergraduate and postgraduate programs',source:'https://www.uob.edu.pk/'},
{name:'Balochistan University of Engineering & Technology',city:'Khuzdar',type:'Public',focus:'Engineering and technology',source:'https://www.buetk.edu.pk/'},
{name:'University of Turbat',city:'Turbat',type:'Public',focus:'Programs serving southern Balochistan',source:'https://uot.edu.pk/'},
{name:'Lasbela University of Agriculture, Water & Marine Sciences',city:'Uthal',type:'Public',focus:'Agriculture, water, marine and related disciplines',source:'https://www.luawms.edu.pk/'},
{name:'Balochistan University of Information Technology, Engineering and Management Sciences',city:'Quetta',type:'Public',focus:'Computing, engineering and management',source:'https://www.buitems.edu.pk/'}
];

export const skills=[
{name:'Web Development',level:'Beginner → Advanced',free:'HTML, CSS, JavaScript, Git',outcome:'Build websites and a portfolio.'},
{name:'Python & AI',level:'Beginner → Intermediate',free:'Python, problem solving, data basics',outcome:'Prepare for automation, data and AI.'},
{name:'Freelancing',level:'Beginner',free:'DigiSkills freelancing + communication',outcome:'Understand proposals, portfolios and client work.'},
{name:'Digital Marketing',level:'Beginner → Intermediate',free:'DigiSkills + practice projects',outcome:'Learn content, SEO and digital campaigns.'},
{name:'UI/UX Design',level:'Beginner',free:'Figma/community learning',outcome:'Design usable interfaces and prototypes.'},
{name:'Cloud & DevOps',level:'Intermediate',free:'Linux + cloud fundamentals',outcome:'Build deployment and infrastructure skills.'}
];
