import { ExternalLink, ShieldCheck, FileCheck2, Stethoscope } from 'lucide-react';
import { entranceTests } from '@/lib/data';

const mdcatResults = [
  {title:'Balochistan MDCAT 2026 — successful candidate lists',desc:'Bolan Medical College published MDCAT 2026 successful-candidate lists covering medical institutions including Mekran, Loralai, Jhalawan and BDS at Bolan Medical College.',url:'https://bmc.edu.pk/?p=5435',meta:'BMC · published 24 March 2026'},
  {title:'Balochistan MDCAT 2025–26 — later merit lists',desc:'Bolan Medical College also published later merit lists for BDS/MBBS admissions in Balochistan public medical colleges.',url:'https://bmc.edu.pk/?p=5636',meta:'BMC · published 15 June 2026'},
  {title:'Punjab MDCAT 2026 result',desc:'University of Health Sciences currently lists the MDCAT 2026 result and a result recount/review portal for candidates seeking admission in Punjab.',url:'https://www.uhs.edu.pk/',meta:'UHS · official 2026 result notice'},
  {title:'PM&DC MDCAT notices',desc:'Use the national regulator for current MDCAT notices, rescheduling information and medical/dental admission policy.',url:'https://www.pmdc.pk/Publication/PressReleases',meta:'PM&DC · official notices'},
];

export default function Tests(){return <>
  <section className="page-hero rich-hero"><div className="container"><span className="eyebrow">🧪 Entrance Tests & Admissions</span><h1>Know the test before you miss the admission.</h1><p>Directorate tests, HEC USAT/LAT/HAT, MDCAT, NUMS MDCAT, KMU-CAT, ECAT, NUST NET, NTS NAT and university-specific tests — organized by when students usually need them.</p><div className="notice success"><ShieldCheck size={15}/> Test requirements are university- and program-specific. Verify the current admission notice.</div></div></section>

  <section className="section"><div className="container"><div className="section-head"><div><span className="section-kicker">Medical admissions</span><h2>MDCAT results & merit lists</h2><p>For Balochistan, keep both the national MDCAT notices and the local medical-college merit lists in your bookmarks.</p></div><a className="btn btn-secondary" href="https://pmdc.pk/" target="_blank" rel="noreferrer">PM&DC official <ExternalLink size={14}/></a></div><div className="result-grid">{mdcatResults.map(r=><a className="result-card result-link-card" href={r.url} target="_blank" rel="noreferrer" key={r.title}><div className="result-icon"><FileCheck2 size={20}/></div><h3>{r.title}</h3><p>{r.desc}</p><span>{r.meta} <ExternalLink size={12}/></span></a>)}</div></div></section>

  <section className="section section-alt"><div className="container"><div className="section-head"><div><span className="section-kicker">Test directory</span><h2>Entrance tests students commonly need</h2><p>Use the official portal linked on each card. A test being listed here does not mean every university requires it.</p></div></div><div className="test-grid">{entranceTests.map(t=><article className="card test-card" key={t.name}><div className="card-top"><span className="tag">{t.stage}</span><span className="verified-pill">Official source</span></div><h2>{t.name}</h2><p><b>Field:</b> {t.field}</p><p>{t.desc}</p><div className="test-source"><span>{t.source}</span><a href={t.url} target="_blank" rel="noreferrer">Open portal <ExternalLink size={13}/></a></div></article>)}</div></div></section>

  <section className="section"><div className="container"><div className="two-col"><div className="card"><h2>After Matric</h2><p>Start with college admission routes, Directorate reserved seats where advertised, cadet/BRC tests, and your chosen FSc/ICS/FA/I.Com/DAE path.</p><a className="btn btn-primary" href="/study-after-matric">Study After Matric</a></div><div className="card"><h2>After 12th / HSSC</h2><p>Prepare for the test your target degree actually uses: MDCAT/NUMS for medicine, LAT for law, USAT where accepted, ECAT/NET/NAT and university-specific tests.</p><a className="btn btn-primary" href="/careers">Explore careers</a></div></div></div></section>
</> }
