import Link from 'next/link';
import {ArrowRight,ShieldCheck} from 'lucide-react';
import {scholarships} from '@/lib/data';
import {ScholarshipCard} from '@/components/ScholarshipCard';
const groups=[
 {title:'🎓 BS / Bachelor Abroad',desc:'For students after Intermediate. Look at level-specific requirements, tests, documents and university admission rules.',items:scholarships.filter(s=>s.category==='BS Abroad')},
 {title:'🎓 Masters Abroad',desc:'For students who already have a Bachelor’s degree. Many routes require a strong academic record and program-specific documents.',items:scholarships.filter(s=>s.category==='Masters Abroad'&&s.level.includes('Masters'))},
 {title:'🔬 PhD Abroad',desc:'For researchers and graduates. Funding and admission can depend heavily on the university, research area and supervisor.',items:scholarships.filter(s=>s.level.includes('PhD'))}
];
export default function Abroad(){return <><section className="page-hero"><div className="container"><span className="eyebrow">🌍 Study Abroad</span><h1>Plan abroad study by your degree level.</h1><p>BS, Master’s and PhD applications are not the same. TaleemAI separates them so students can understand what applies to them and what is “not yet”.</p><div className="notice success"><ShieldCheck size={15}/> International scholarship facts below are linked to official providers. Always verify the current cycle before applying.</div></div></section><section className="section"><div className="container"><div className="timeline"><div className="step"><span className="step-num">1</span><div><h3>After Matric / Intermediate</h3><p className="muted">Build academics, English, passport/documents and a realistic list of undergraduate routes. Some programs have tests or extra requirements.</p></div></div><div className="step"><span className="step-num">2</span><div><h3>During Bachelor’s</h3><p className="muted">Build projects, research exposure, references and a strong academic record. Start tracking Master’s funding early.</p></div></div><div className="step"><span className="step-num">3</span><div><h3>After Bachelor’s</h3><p className="muted">Compare Erasmus Mundus, Commonwealth, Fulbright, Chevening and university-specific funding where the level and requirements fit.</p></div></div><div className="step"><span className="step-num">4</span><div><h3>For PhD</h3><p className="muted">Look for funded doctoral routes, research fit, supervisor requirements and country/university-specific admission rules.</p></div></div></div></div></section>{groups.map(g=><section className="section alt" key={g.title}><div className="container"><div className="section-head"><div><h2>{g.title}</h2><p>{g.desc}</p></div></div><div className="scholarship-grid">{g.items.map(s=><ScholarshipCard key={s.id} s={s}/>)}</div></div></section>)}<section className="section"><div className="container banner"><div><span className="eyebrow">🤖 Need a personal route?</span><h2>Tell TaleemAI where you are now.</h2><p>Give your education level, marks, district, age and target field. The Mentor can explain which routes are relevant now, later, or need verification.</p></div><Link className="btn btn-primary" href="/mentor">Open AI Mentor <ArrowRight size={15}/></Link></div></section></>}
